/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C_1.h"
#include "I2C_1_I2C.h"
#include "I2C_1_PINS.h"
#include "I2C_1_I2C_PVT.h"
#include "I2C_1_PVT.h"
#include "I2C_1_BOOT.h"
#include "DebugLEDRed.h"
#include "DebugLEDRed_aliases.h"
#include "DebugLEDGreen.h"
#include "DebugLEDGreen_aliases.h"
#include "DebugLEDBlue.h"
#include "DebugLEDBlue_aliases.h"
#include "MotorXAxisDirectionLeft.h"
#include "MotorXAxisDirectionLeft_aliases.h"
#include "MotorXAxisDirectionRight.h"
#include "MotorXAxisDirectionRight_aliases.h"
#include "PWM_Y_UP.h"
#include "PWM_X_RIGHT.h"
#include "PWM_X_LEFT.h"
#include "Clock_PWM_1.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "ADC_1.h"
#include "PWM_Y_DOWN.h"
#include "MotorYAxisDirectionUp.h"
#include "MotorYAxisDirectionUp_aliases.h"
#include "MotorYAxisDirectionDown.h"
#include "MotorYAxisDirectionDown_aliases.h"
#include "Shoot.h"
#include "Shoot_aliases.h"
#include "I2C_1_SCBCLK.h"
#include "I2C_1_sda.h"
#include "I2C_1_sda_aliases.h"
#include "I2C_1_scl.h"
#include "I2C_1_scl_aliases.h"
#include "I2C_1_SCB_IRQ.h"
#include "ADC_1_IRQ.h"
#include "ADC_1_intClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

