# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\PernilleLouise\Documents\Elektro\3. semester\E3PRJ3\Hardware\Motorstyring\Motorstyring.cydsn\Motorstyring.cyprj
# Date: Fri, 04 Mar 2016 09:51:59 GMT
#set_units -time ns
create_clock -name {CapSense_CSD_SampleClk(FFB)} -period 10625 -waveform {0 5312.5} [list [get_pins {ClockBlock/ff_div_6}]]
create_clock -name {CapSense_CSD_SenseClk(FFB)} -period 10625 -waveform {0 5312.5} [list [get_pins {ClockBlock/ff_div_5}]]
create_clock -name {Clock_PWM(FFB)} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/ff_div_8}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {CapSense_CSD_SampleClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {CapSense_CSD_SenseClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {Clock_PWM} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 5} [list]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\PernilleLouise\Documents\Elektro\3. semester\E3PRJ3\Hardware\Motorstyring\Motorstyring.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\PernilleLouise\Documents\Elektro\3. semester\E3PRJ3\Hardware\Motorstyring\Motorstyring.cydsn\Motorstyring.cyprj
# Date: Fri, 04 Mar 2016 09:51:57 GMT
