/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "opamp_m.h"
#include "opamp_m_aliases.h"
#include "PWM_out.h"
#include "PWM_out_aliases.h"
#include "Opamp_1.h"
#include "PWM_led.h"
#include "opamp_p.h"
#include "opamp_p_aliases.h"
#include "opamp_out.h"
#include "opamp_out_aliases.h"
#include "Clock_0.h"
#include "ADC_in.h"
#include "ADC_in_aliases.h"
#include "ADC_2.h"
#include "PWM_motor.h"
#include "isr_Shoot.h"
#include "isr_in.h"
#include "isr_in_aliases.h"
#include "Pin_red.h"
#include "Pin_red_aliases.h"
#include "Pin_green.h"
#include "Pin_green_aliases.h"
#include "ADC_2_IRQ.h"
#include "ADC_2_intClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

